templates = [
    'a remote sensing image of many {c}.',
    'a remote sensing image of a {c}.',
    'a remote sensing image of the {c}.',
    'a remote sensing image of the hard to see {c}.',
    'a remote sensing image of a hard to see {c}.',
    'a low resolution remote sensing image of the {c}.',
    'a low resolution remote sensing image of a {c}.',
    'a bad remote sensing image of the {c}.',
    'a bad remote sensing image of a {c}.',
    'a cropped remote sensing image of the {c}.',
    'a cropped remote sensing image of a {c}.',
    'a bright remote sensing image of the {c}.',
    'a bright remote sensing image of a {c}.',
    'a dark remote sensing image of the {c}.',
    'a dark remote sensing image of a {c}.',
    'a close-up remote sensing image of the {c}.',
    'a close-up remote sensing image of a {c}.',
    'a black and white remote sensing image of the {c}.',
    'a black and white remote sensing image of a {c}.',
    'a jpeg corrupted remote sensing image of the {c}.',
    'a jpeg corrupted remote sensing image of a {c}.',
    'a blurry remote sensing image of the {c}.',
    'a blurry remote sensing image of a {c}.',
    'a good remote sensing image of the {c}.',
    'a good remote sensing image of a {c}.',
    'a remote sensing image of the large {c}.',
    'a remote sensing image of a large {c}.',
    'a remote sensing image of the nice {c}.',
    'a remote sensing image of a nice {c}.',
    'a remote sensing image of the small {c}.',
    'a remote sensing image of a small {c}.',
    'a remote sensing image of the weird {c}.',
    'a remote sensing image of a weird {c}.',
    'a remote sensing image of the cool {c}.',
    'a remote sensing image of a cool {c}.',
    'an aerial image of many {c}.',
    'an aerial image of a {c}.',
    'an aerial image of the {c}.',
    'an aerial image of the hard to see {c}.',
    'an aerial image of a hard to see {c}.',
    'a low resolution aerial image of the {c}.',
    'a low resolution aerial image of a {c}.',
    'a bad aerial image of the {c}.',
    'a bad aerial image of a {c}.',
    'a cropped aerial image of the {c}.',
    'a cropped aerial image of a {c}.',
    'a bright aerial image of the {c}.',
    'a bright aerial image of a {c}.',
    'a dark aerial image of the {c}.',
    'a dark aerial image of a {c}.',
    'a close-up aerial image of the {c}.',
    'a close-up aerial image of a {c}.',
    'a black and white aerial image of the {c}.',
    'a black and white aerial image of a {c}.',
    'a jpeg corrupted aerial image of the {c}.',
    'a jpeg corrupted aerial image of a {c}.',
    'a blurry aerial image of the {c}.',
    'a blurry aerial image of a {c}.',
    'a good aerial image of the {c}.',
    'a good aerial image of a {c}.',
    'an aerial image of the large {c}.',
    'an aerial image of a large {c}.',
    'an aerial image of the nice {c}.',
    'an aerial image of a nice {c}.',
    'an aerial image of the small {c}.',
    'an aerial image of a small {c}.',
    'an aerial image of the weird {c}.',
    'an aerial image of a weird {c}.',
    'an aerial image of the cool {c}.',
    'an aerial image of a cool {c}.',
    'a satellite image of many {c}.',
    'a satellite image of a {c}.',
    'a satellite image of the {c}.',
    'a satellite image of the hard to see {c}.',
    'a satellite image of a hard to see {c}.',
    'a low resolution satellite image of the {c}.',
    'a low resolution satellite image of a {c}.',
    'a bad satellite image of the {c}.',
    'a bad satellite image of a {c}.',
    'a cropped satellite image of the {c}.',
    'a cropped satellite image of a {c}.',
    'a bright satellite image of the {c}.',
    'a bright satellite image of a {c}.',
    'a dark satellite image of the {c}.',
    'a dark satellite image of a {c}.',
    'a close-up satellite image of the {c}.',
    'a close-up satellite image of a {c}.',
    'a black and white satellite image of the {c}.',
    'a black and white satellite image of a {c}.',
    'a jpeg corrupted satellite image of the {c}.',
    'a jpeg corrupted satellite image of a {c}.',
    'a blurry satellite image of the {c}.',
    'a blurry satellite image of a {c}.',
    'a good satellite image of the {c}.',
    'a good satellite image of a {c}.',
    'a satellite image of the large {c}.',
    'a satellite image of a large {c}.',
    'a satellite image of the nice {c}.',
    'a satellite image of a nice {c}.',
    'a satellite image of the small {c}.',
    'a satellite image of a small {c}.',
    'a satellite image of the weird {c}.',
    'a satellite image of a weird {c}.',
    'a satellite image of the cool {c}.',
    'a satellite image of a cool {c}.',
]
