templates = [
    'a satellite image showing {c}.',
    'a satellite image showing a {c}.',
    'a satellite image showing the {c}.',
    'The image is a satellite view showing {c}.',
    'The image is a satellite view showing a {c}.',
    'The image is a satellite view showing the {c}.',
    'The image shows {c}',
    'a satellite image of {c}.',
    'a satellite image of a {c}.',
    'a satellite image of the {c}.',
    'the satellite image of {c}.',
    'the satellite image of a {c}.',
    'the satellite image of the {c}.',
    'a satellite view of {c}.',
    'a satellite view of a {c}.',
    'a satellite view of the {c}.',
    'a low resolution satellite image of the {c}.',
    'a low resolution satellite image of a {c}.',
    'a bad satellite image of the {c}.',
    'a bad satellite image of a {c}.',
    'a cropped satellite image of the {c}.',
    'a cropped satellite image of a {c}.',
    'a bright satellite image of the {c}.',
    'a bright satellite image of a {c}.',
    'a cropped aerial image of the {c}.',
    'a cropped aerial image of a {c}.',
    'a bright aerial image of the {c}.',
    'a bright aerial image of a {c}.',
    'a dark aerial image of the {c}.',
    'a dark aerial image of a {c}.',
    'a close-up aerial image of the {c}.',
    'a close-up aerial image of a {c}.',
    'a black and white aerial image of the {c}.',
    'a black and white aerial image of a {c}.',
    'a jpeg corrupted aerial image of the {c}.',
    'a jpeg corrupted aerial image of a {c}.',
    'a blurry aerial image of the {c}.',
    'a blurry aerial image of a {c}.',
    'a good aerial image of the {c}.',
    'a good aerial image of a {c}.',
    'an aerial image of the large {c}.',
    'an aerial image of a large {c}.',
    'an aerial image of the nice {c}.',
    'an aerial image of a nice {c}.',
    'an aerial image of the small {c}.',
    'an aerial image of a small {c}.',
    'an aerial image of the weird {c}.',
    'an aerial image of a weird {c}.',
    'an aerial image of the cool {c}.',
    'an aerial image of a cool {c}.',
    
      ]